name: CI

on: [push, pull_request]

jobs:
  migrations:
    runs-on: ubuntu-latest
    env:
      # Ensure the project root is on PYTHONPATH
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip & install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install the crypto-trading-tool package
        run: pip install -e .

      - name: Run Alembic migrations
        # If your alembic.ini lives in a subfolder, set working-directory
        working-directory: crypto-trading-tool
        run: alembic upgrade head
